package org.opensources.umai.youtube.data

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.opensources.umai.recipe.domain.VideoStream
import org.opensources.umai.youtube.domain.ChapterMark
import org.opensources.umai.youtube.domain.TranscriptCue
import org.opensources.umai.youtube.domain.VideoDescription
import org.opensources.umai.youtube.domain.VideoSource
import org.opensources.umai.youtube.domain.YouTubeFailure
import org.opensources.umai.youtube.domain.YouTubeLinks
import org.opensources.umai.youtube.domain.YouTubeResult
import org.opensources.umai.youtube.domain.YouTubeVideo
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException
import org.schabi.newpipe.extractor.exceptions.ExtractionException
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException
import org.schabi.newpipe.extractor.exceptions.SignInConfirmNotBotException
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.localization.Localization
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamType
import java.io.IOException

/**
 * Reads YouTube videos with NewPipeExtractor, with no account and no API key:
 * the details, the author's chapters and the captions for the import, and a
 * stream for the cooking mode. NewPipeExtractor is maintained against
 * YouTube's frequent changes; when YouTube breaks it, updating the library
 * (`newpipeExtractor` in `gradle/libs.versions.toml`) is the fix.
 */
class YouTubeClient(
    private val http: OkHttpClient,
    /** "fr" or "en": the language the page is asked in, which YouTube translates some descriptions to. */
    private val language: () -> String,
) : VideoSource {

    init {
        // NewPipeExtractor keeps its downloader in a global; there is one per app.
        NewPipe.init(OkHttpDownloader(http))
    }

    /** The video with its description, chapters and transcript. */
    override suspend fun video(id: String): YouTubeResult<YouTubeVideo> = read(id) { info ->
        val description = YouTubeMarkup.descriptionText(info.description.content.orEmpty())
        val track = CaptionChoice.preferred(
            tracks = info.subtitles.map { CaptionTrack(it.content, it.languageTag, it.isAutoGenerated) },
            spokenLanguage = info.audioStreams.firstOrNull { it.audioTrackType == AudioTrackType.ORIGINAL }
                ?.audioLocale?.language,
        )
        YouTubeVideo(
            id = id,
            title = info.name.orEmpty(),
            author = info.uploaderName.orEmpty(),
            description = description,
            durationSeconds = info.duration.toInt(),
            thumbnailUrl = info.thumbnails.maxByOrNull { it.width }?.url,
            chapters = info.streamSegments.map { ChapterMark(it.title.trim(), it.startTimeSeconds.toDouble()) }
                .ifEmpty { VideoDescription.timestamps(description) },
            transcript = track?.let { captions(it.url) }.orEmpty(),
            transcriptAutomatic = track?.automatic == true,
        )
    }

    /**
     * A stream of the video the player can read, looked up right before it is
     * played: the addresses YouTube gives expire after a few hours. HLS when
     * YouTube offers it, for its adaptive quality; else the best progressive
     * file with picture and sound together.
     */
    suspend fun stream(id: String): VideoStream? =
        (read(id) { info ->
            info.hlsUrl?.takeIf { it.isNotBlank() }?.let { VideoStream(it, isHls = true) }
                ?: info.videoStreams
                    .filter { !it.isVideoOnly() && it.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP && it.isUrl }
                    .maxByOrNull { it.height }
                    ?.let { VideoStream(it.content, isHls = false) }
        } as? YouTubeResult.Success)?.value

    private suspend fun <T> read(id: String, map: (StreamInfo) -> T): YouTubeResult<T> = withContext(Dispatchers.IO) {
        try {
            val extractor = ServiceList.YouTube.getStreamExtractor(YouTubeLinks.watchUrl(id))
            // Set on the extractor: NewPipe's global preference does not reach
            // every request it makes for the video.
            val lang = language()
            extractor.forceLocalization(Localization(lang))
            extractor.forceContentCountry(ContentCountry(if (lang == "fr") "FR" else "US"))
            val info = StreamInfo.getInfo(extractor)
            // A live still running has neither a length nor a transcript yet: there is no recipe to rebuild.
            if (info.streamType == StreamType.LIVE_STREAM) return@withContext YouTubeResult.Failure(YouTubeFailure.UNAVAILABLE)
            YouTubeResult.Success(map(info))
        } catch (cause: CancellationException) {
            throw cause
        } catch (_: SignInConfirmNotBotException) {
            YouTubeResult.Failure(YouTubeFailure.BLOCKED)
        } catch (_: ReCaptchaException) {
            YouTubeResult.Failure(YouTubeFailure.BLOCKED)
        } catch (_: ContentNotAvailableException) {
            YouTubeResult.Failure(YouTubeFailure.UNAVAILABLE)
        } catch (_: ExtractionException) {
            YouTubeResult.Failure(YouTubeFailure.UNREADABLE)
        } catch (_: IOException) {
            YouTubeResult.Failure(YouTubeFailure.NETWORK)
        }
    }

    /** A caption track, as TTML; a track that cannot be read leaves the video without transcript. */
    private fun captions(url: String): List<TranscriptCue> = try {
        http.newCall(Request.Builder().url(url).build()).execute().use { response ->
            if (response.isSuccessful) YouTubeMarkup.ttmlCues(response.body.string()) else emptyList()
        }
    } catch (_: IOException) {
        emptyList()
    }
}

/** A caption track offered for a video. */
internal data class CaptionTrack(val url: String, val languageTag: String, val automatic: Boolean)

internal object CaptionChoice {

    /**
     * The best transcript: in the language the video is spoken in, written by
     * a person, else the automatic one. YouTube also offers automatic tracks in
     * the languages it dubs a video into: the spoken language, when the
     * original sound track does not give it, is that of the only automatic track.
     */
    fun preferred(tracks: List<CaptionTrack>, spokenLanguage: String?): CaptionTrack? {
        val spoken = spokenLanguage ?: tracks.singleOrNull { it.automatic }?.language
        val inSpoken = tracks.filter { spoken == null || it.language == spoken }
        return inSpoken.firstOrNull { !it.automatic }
            ?: inSpoken.firstOrNull { it.automatic }
            ?: tracks.firstOrNull { !it.automatic }
            ?: tracks.firstOrNull()
    }

    private val CaptionTrack.language: String get() = languageTag.substringBefore('-').lowercase()
}
