import java.net.URI
import java.security.MessageDigest
import java.util.Properties
import java.util.zip.ZipInputStream

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.compiler)
}

// Kept outside this script so the CI can bump it on every push to main (docs/release.md).
val appVersion = Properties().apply {
    load(providers.fileContents(layout.projectDirectory.file("version.properties")).asText.get().reader())
}

android {
    namespace = "org.opensources.umai"
    compileSdk = 37
    // Strips the native libraries of LiteRT-LM packaged in the APK.
    ndkVersion = "30.0.16248370"

    defaultConfig {
        applicationId = "org.opensources.umai"
        minSdk = 37
        targetSdk = 37
        versionCode = checkNotNull(appVersion.getProperty("versionCode")).toInt()
        versionName = checkNotNull(appVersion.getProperty("versionName"))

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // The on-device language model (LiteRT-LM) is packaged for 64-bit ARM
        // only: every phone that runs Android 17 has it, and a model this size
        // would not run usefully on anything else.
        ndk {
            abiFilters += "arm64-v8a"
        }
    }

    androidResources {
        // Umai ships English (default) and French; any other system language
        // falls back to the default resources, i.e. English.
        localeFilters += setOf("en", "fr")
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
        }
    }

    packaging {
        resources.excludes += setOf("/META-INF/{AL2.0,LGPL2.1}")
        // LiteRT-LM loads the Tensor TPU dispatch library from the native
        // library directory, by path; left inside the APK, the library is not
        // in that directory and the TPU is never reached.
        jniLibs.useLegacyPackaging = true
    }

    lint {
        warningsAsErrors = false
        abortOnError = true
        // PropertyEscape only ever fires on `local.properties`, a machine-local
        // file that is generated by the IDE, excluded from git and never
        // shipped; on Windows it flags the SDK path whichever way it is written.
        disable += "PropertyEscape"
        // The app is built for arm64-v8a only, on purpose: the on-device language
        // model it bundles LiteRT-LM for would not run usefully on x86_64 hardware.
        disable += "ChromeOsAbiSupport"
        checkDependencies = true
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.splashscreen)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.datastore.preferences)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material3.window)
    implementation(libs.compose.material.icons.extended)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)

    implementation(libs.retrofit)
    implementation(libs.retrofit.serialization)
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)

    implementation(libs.coil.compose)
    implementation(libs.coil.network.okhttp)

    // Plays the step-by-step cooking videos some recipe sources publish, and
    // YouTube videos, which come as HLS playlists.
    implementation(libs.media3.exoplayer)
    implementation(libs.media3.exoplayer.hls)
    implementation(libs.media3.ui.compose)

    // Reads YouTube videos: details, chapters, captions and streams (GPLv3).
    implementation(libs.newpipe.extractor)

    // Runs the on-device language model on the TPU, the GPU or the CPU (Apache 2.0).
    implementation(libs.litertlm.android)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.okhttp.mockwebserver)
    testImplementation(libs.turbine)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)

    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.test.espresso)
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.compose.ui.test.junit4)
    androidTestImplementation(libs.kotlinx.coroutines.test)
}

/**
 * Fetches the Google Tensor dispatch library of LiteRT, through which LiteRT-LM
 * runs a model on the TPU of a Tensor G5 or G6: it hands the compiled model to
 * the phone's own TPU driver (`libedgetpu_litert.so`, in the vendor partition).
 * Google publishes it prebuilt with each LiteRT release (Apache 2.0, built from
 * `litert/vendors/google_tensor/dispatch`); it is downloaded at a pinned
 * release, checked against its hash and never committed.
 */
abstract class FetchTensorDispatch : DefaultTask() {

    @get:Input
    abstract val url: Property<String>

    @get:Input
    abstract val sha256: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun fetch() {
        val archive = URI(url.get()).toURL().openStream().use { it.readBytes() }
        val digest = MessageDigest.getInstance("SHA-256").digest(archive)
            .joinToString("") { "%02x".format(it) }
        check(digest.equals(sha256.get(), ignoreCase = true)) { "Unexpected hash for ${url.get()}: $digest" }
        val target = outputDir.get().dir("arm64-v8a").asFile.apply { mkdirs() }.resolve(LIBRARY)
        ZipInputStream(archive.inputStream()).use { zip ->
            generateSequence { zip.nextEntry }.first { it.name == "$ENTRY_DIR/$LIBRARY" }
            target.outputStream().use { zip.copyTo(it) }
        }
    }

    private companion object {
        const val ENTRY_DIR = "google_tensor_runtime/src/main/jni/arm64-v8a"
        const val LIBRARY = "libLiteRtDispatch_GoogleTensor.so"
    }
}

val fetchTensorDispatch = tasks.register<FetchTensorDispatch>("fetchTensorDispatch") {
    url.set("https://github.com/google-ai-edge/LiteRT/releases/download/v2.1.6/litert_npu_runtime_libraries.zip")
    sha256.set("98aabbdce8607f6dc6ab7cb92217326eef24a8c97b973b69e62bd0ce14b7495b")
    outputDir.set(layout.buildDirectory.dir("tensor-dispatch"))
}

androidComponents {
    onVariants { variant ->
        variant.sources.jniLibs?.addGeneratedSourceDirectory(fetchTensorDispatch, FetchTensorDispatch::outputDir)
    }
}
